services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_coach_serverpod_challenge
      POSTGRES_PASSWORD: "XCV9UsKVAPKe7a168YjbX3DhYlKCEQb1"
    volumes:
      - my_coach_serverpod_challenge_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "P2YhaacQeB6fL9Qx-lkQx7fm1zrGKXYD"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_coach_serverpod_challenge_test
      POSTGRES_PASSWORD: "mOBvI5ejoYiFqo0q2suzSQPKs6yZcwTJ"
    volumes:
      - my_coach_serverpod_challenge_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "gpCVQU57KORY8lIPPJDwsy_YoNyeSZvZ"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  my_coach_serverpod_challenge_data:
  my_coach_serverpod_challenge_test_data:
